# Based on https://github.com/marzent/IINACT/blob/main/.github/workflows/build.yml

name: Plugin Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: '0.0.0.0'
      DALAMUD_HOME: /tmp/dalamud
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Download Dalamud
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip /tmp/dalamud
      - name: Build Plugin
        run: dotnet build -c release
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: MemoMate
      #     path: MemoMate/bin/Release/*
      - name: Make Release Zip
        shell: pwsh
        run: |
          Compress-Archive -Path './MemoMate/bin/Release/*' -DestinationPath './release.zip'
      - name: Get Assembly Version
        shell: pwsh
        run: |
          $version = Get-Command("./MemoMate/bin/Release/MemoMate.dll").FileVersionInfo.FileVersion
          Write-Output "RELEASE_VERSION=$version" >> $env:GITHUB_ENV
          echo $version
      - name: Create Release
        if: ${{ env.RELEASE_VERSION != '0.0.0.0' }}
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
          name: MemoMate ${{ env.RELEASE_VERSION }}
          tag_name: release-${{ env.RELEASE_VERSION }}
