# Based on https://github.com/marzent/IINACT/blob/main/.github/workflows/build.yml
name: Plugin Build

on:
  push:
    branches: [ "main" ]

env:
  PLUGIN_NAME: MemoMate
  DALAMUD_HOME: /tmp/dalamud

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Download Dalamud
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip /tmp/dalamud
      - name: Build Plugin
        run: dotnet build -c release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: $PLUGIN_NAME
          path: $PLUGIN_NAME/bin/Release/*